version: '3.8'

networks:
  web:
    external: true
    name: traefik_web

services:
  tinyrelay:
    build: .
    image: tinyrelay:latest
    container_name: tinyrelay
    restart: unless-stopped
    expose:
      - "9050"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # UDP Router
      - "traefik.udp.routers.tinyrelay.entrypoints=udp"
      - "traefik.udp.routers.tinyrelay.service=tinyrelay"
      - "traefik.udp.services.tinyrelay.loadbalancer.server.port=9050"
